on:
  pull_request:
    branches:
      - master

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Run version checker
    steps:
      - uses: actions/checkout@v2
      - name: Check version
        uses: ./
        id: checker
      - name: Results
        run: echo "Version is ${{ steps.checker.outputs.version }}"
