on:
  pull_request:
    branches:
      - master

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Run version checker
    steps:
      - uses: actions/checkout@v4
      - name: Check version from default file (package.json)
        uses: ./
        id: checker1
      - name: Default file result
        run: echo "Version is ${{ steps.checker1.outputs.version }}"
      - name: Check version from custom file (VERSION)
        uses: ./
        id: checker2
        env:
          INPUT_FILE: "VERSION"
      - name: Custom file result
        run: echo "Version is ${{ steps.checker2.outputs.version }}"
